name: kapix_citation
description: AI-powered citation assistant for law enforcement
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # State Management
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  
  # Chat UI
  flutter_chat_ui: ^2.9.0
  flutter_chat_types: ^3.6.2
  
  # Multi-modal inputs
  image_picker: ^1.0.4
  camera: ^0.11.2
  speech_to_text: ^7.2.0
  permission_handler: ^12.0.1
  
  # Document processing
  google_mlkit_text_recognition: ^0.15.0
  
  # PDF handling - Using correct packages
  pdf: ^3.10.7
  printing: ^5.11.1
  syncfusion_flutter_pdf: ^30.1.42
  
  # Utilities
  uuid: ^4.2.1
  intl: ^0.20.2
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  riverpod_generator: ^2.3.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/templates/
    - assets/templates/california/